name: glial-neuron-pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pandas>=1.5.0
  - numpy>=1.21.0
  - matplotlib>=3.5.0
  - scipy>=1.9.0
  - scikit-learn>=1.1.0
  - seaborn>=0.11.0
  - plotly>=5.0.0
  - openpyxl>=3.0.0
  - xlrd>=2.0.0
  - h5py>=3.7.0
  - python-dateutil>=2.8.0
  - pip
  - pip:
    - tkinter-tooltip>=2.2.0
